# Generated by Django 5.2.17 on 2026-09-20 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('regra', 'Regra de uso'), ('manutencao', 'Manutenção programada')], default='aviso', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('escola', 'Escola'), ('creche', 'Creche'), ('orfanato', 'Orfanato'), ('asilo', 'Asilo'), ('ong', 'ONG'), ('esportivo', 'Grupo esportivo'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agenda.grupo')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.horario')),
            ],
            options={
                'ordering': ['data', 'horario__hora_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmado')), fields=('horario', 'data'), name='unico_agendamento_confirmado_por_horario_data')],
            },
        ),
    ]
